services:

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./src/main/resources/templates:/usr/share/nginx/html
    restart: always

  BTLab-server:
    build: ./
    image: btlab-server
    container_name: btlab-server
    ports:
      - "8080:8080"
    depends_on:
      - BTLab-db
    environment:
      - DB_NAME=btlab
      - USER=root
      - PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  BTLab-db:
    image: postgres:14-alpine
    container_name: btlab-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=btlab
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root