drop table if exists users cascade;
drop table if exists reason cascade;
drop table if exists truancy cascade;

create table if not exists users (
user_id bigint not null generated by default as identity primary key,
last_name varchar(100) not null,
first_name varchar(100) not null,
patronymic varchar(100),
date_of_bird timestamp without time zone not null,
email varchar(320) UNIQUE not null,
telephone varchar(11) UNIQUE not null,
passport_series varchar(4) not null,
passport_number varchar(6) not null,
passport_issued varchar(320) not null,
passport_date timestamp without time zone not null,
passport_kp varchar(6) not null
);

create table if not exists reason (
reason_id bigint not null generated by default as identity primary key,
name varchar(10) not null
);

create table if not exists truancy (
truancy_id bigint not null generated by default as identity primary key,
reason bigint not null references reason(reason_id),
start_date timestamp without time zone not null,
duration int not null,
discounted boolean not null,
description varchar(1024) not null,
user_id bigint not null references users(user_id)
);